### ISSUE TITLE
Python email request handler

### ISSUE THREAD

**Issue by rickyschoolsFS** [rickyschoolsFS/ListManagement#100]
Format to list management team should match the below. 

Need to account for contextual sending (i.e. Emails from FS Investments should be funneled into an email folder)

If emails have no attachments the request or should get an email. 

If the email is identified as a 'good request' then the requestor should get an email that the list was received and will be added to the queue. 

https://trello.com/b/KhPmn9qK/sf-lists-leads

Sent by: Kari Whitman
Received on: 5/15/2017 11:14:14 AM
Subject: FW Q1 2017 Advisor Lists

Navigate to the 'Pending Files - Needs Pre-Processing' folder within the Search Program and find the new 'Cetera Q1 2017 - Advisor Report - Alternative Investments.xlsx' file, which is in need of pre-processing.

With questions reach out to ricky.schools@fsinvestments.com 

- List Management App

**Comment by rickyschoolsFS** [comment]
Also consider creating a list record directly from these emails. 

Would need
- an object I'd (or link to parse)
- an object to link an attachment (if attachments are present

**Comment by rickyschoolsFS** [comment]
Currently fighting this error message when attempting to attach files to a record.

Traceback (most recent call last):
  File "C:\AllShare\GitHub\ListManagement\sf\sf_wrapper.py", line 133, in upload_attachments
    AttachmentWriter.attachFile(session=self.session, parentId=obj_id, filename=att)
  File "C:\Python27\lib\site-packages\SQLForce\AttachmentWriter.py", line 42, in attachFile
    idList = session.insert('Attachment', ['parentId', 'contentType', 'description', 'name', 'body'], [record])
  File "C:\Python27\lib\site-packages\SQLForce\__init__.py", line 240, in insert
    raise Exception( result.message )
Exception: java.lang.IllegalStateException: Form too large 1941958>200000
	at org.eclipse.jetty.server.Request.extractParameters(Request.java:339)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:827)
	at com.capstorm.servlet.common.ServletParameterReader.getAnyParameter(ServletParameterReader.java:67)
	at com.capstorm.servlet.common.ServletParameterReader.getOptionalString(ServletParameterReader.java:72)
	at com.capstorm.servlet.common.ServletParameterReader.getRequiredString(ServletParameterReader.java:77)
	at com.aslan.sfdc.sqlforce.server.InsertServlet.doPost(InsertServlet.java:81)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1568)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1539)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:453)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:459)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:280)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.lang.Thread.run(Unknown Source)
