### ISSUE TITLE
NaN rows are impacting List processing

### ISSUE THREAD

**Issue by rickyschoolsFS** [rickyschoolsFS/ListManagement#77]
There are times when lists have extra (invisible) rows included. We should find a way to remove all rows that don't have any data associated with them.

**Experiencing:**
87           Jon
88           Ben
89           NaN
90           NaN

**Should only be working with:**
87           Jon
88           Ben

This issue impacts the 'strip_unicode_chars' in the finra_helpers module.

```
def strip_unicode_chars(row):
    """
    attempts to remove all unicode data from the row values.

    :param row: cell value with unicode chars
    :return: transformed cell value without unicode chars
    """
    return [unicodedata.normalize('NFKD', str(r)).encode('utf-8', 'ignore') for r in row]

```

**The error received is the following:**
>>> df['First Name'].apply(strip_unicode_chars)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pandas\core\series.py", line 2294, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\src\inference.pyx", line 1207, in pandas.lib.map_infer (pandas\lib.c:66124)
  File "C:\Users\rschools\Documents\GitHub\ListManagement\utility\finra_helpers.py", line 13, in strip_unicode_chars
    return [unicodedata.normalize('NFKD', r).encode('utf-8', 'ignore') for r in row]
TypeError: 'float' object is not iterable

**Comment by rickyschoolsFS** [comment]
we may be able to close this issue by using the pandas .dropna(axis=0, how='all') method with the specified parameters.
